steps:
  - name: 'node:10'
    entrypoint: npm
    args: ['install']
  - name: 'node:10'
    entrypoint: npm
    args: ['run', 'affected:build', '--', '--base=$SHORT_SHA~1', '--head=$SHORT_SHA']
#  - name: 'node:10'
#    entrypoint: npm
#    args: ['run', 'build:frontend']


  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: ./ci.sh
    args:
      - '$PROJECT_ID'
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: ./cd.sh
    args:
      - '$PROJECT_ID'
#    args:
#      - 'build'
#      - '--tag=gcr.io/$PROJECT_ID/backend'
#      - '--file=Dockerfile'
#      - '--cache-from'
#      - 'gcr.io/$PROJECT_ID/backend:latest'
#      - '.'
#  - name: 'gcr.io/cloud-builders/docker'
#    args:
#      - 'build'
#      - '--tag=gcr.io/$PROJECT_ID/frontend'
#      - '--file=Dockerfile'
#      - '--cache-from'
#      - 'gcr.io/$PROJECT_ID/frontend:latest'
#      - '.'

