steps:
  - name: 'node:10'
    entrypoint: npm
    args: ['install']
  - name: 'node:10'
    entrypoint: npm
    args: ['run', 'affected:build']
#  - name: 'node:10'
#    entrypoint: npm
#    args: ['run', 'build:frontend']


  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--tag=gcr.io/$PROJECT_ID/backend'
      - '--file=api.Dockerfile'
      - '--cache-from'
      - 'gcr.io/$PROJECT_ID/backend:latest'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--tag=gcr.io/$PROJECT_ID/frontend'
      - '--file=frontend.Dockerfile'
      - '--cache-from'
      - 'gcr.io/$PROJECT_ID/frontend:latest'
      - '.'
images:
  - 'gcr.io/$PROJECT_ID/backend'
  - 'gcr.io/$PROJECT_ID/frontend'
