steps:
  - name: 'node:10'
    entrypoint: npm
    args: ['install']
  - name: 'node:10'
    entrypoint: npm
    args: ['run', 'build:backend']
  - name: 'node:10'
    entrypoint: npm
    args: ['run', 'build:frontend']
  - name: 'gcr.io/$PROJECT_ID/docker-compose'
    args: ['up']
