steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install', '--production']
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
  - name: 'gcr.io/$PROJECT_ID/docker-compose'
    args: ['up']
