steps:
  - name: 'gcr.io/cloud-builders'
    args: ['install', '-g', '@angular/cli']
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
  - name: 'gcr.io/$PROJECT_ID/docker-compose'
    args: ['up']
