version: '3'
services:
  backend:
    container_name: backend
    image: backend
    networks:
      - jwt
  frontend:
    container_name: frontend
    image: frontend
    ports:
      - 8080:80
    networks:
      - jwt
networks:
  jwt:

