version: '3'
services:
  backend:
#    build:
#      dockerfile: backend.Dockerfile
#      context: .
    container_name: backend
    image: gcr.io/ctfd-233822/backend
    networks:
      - jwt
  frontend:
#    build:
#      dockerfile: frontend.Dockerfile
#      context: .
    container_name: frontend
    image: gcr.io/ctfd-233822/frontend
    ports:
      - 8080:80
    networks:
      - jwt
networks:
  jwt:

